logging:
  level:
    org:
      springframework: ERROR
server:
  port: 8889
  servlet:
    context-path: /customer

spring:
  application:
    name: customer
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
