server:
  port: 9011

spring:
  application:
    name: monitoring
eureka:
  client:
    serviceUrl:
      defautlZone: http://localhost:8761/eureka

management:
  security:
    enabled: false
  endpoints:
    web:
      #base-path: /
      exposure:
        include: '*'

turbine:
  appConfig: customer
  clusterNameExpression: new String("default")