version: "3.2"

services:

  postgres-compose:
   image: postgres
   environment:
     POSTGRES_PASSWORD: "Postgres2019!"
   ports:
     - "15432:5432"
   networks:
     - akumo-native-cloud
   container_name: postgres-container

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "akumoplatform@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - akumo-native-cloud

networks:
  akumo-native-cloud:
    driver: bridge
